/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsyncTable: typeof import('./components/AsyncTable/AsyncTable.vue')['default']
    DictRadioGroup: typeof import('./components/DictRadioGroup/DictRadioGroup.vue')['default']
    DictSelect: typeof import('./components/DictSelect/DictSelect.vue')['default']
    DictTag: typeof import('./components/DictTag/DictTag.vue')['default']
    EChart: typeof import('./components/EChart/index.vue')['default']
    IconPicker: typeof import('./components/IconPicker/IconPicker.vue')['default']
    IconSelector: typeof import('./components/IconPicker/IconSelector.vue')['default']
    LabelWithTooltip: typeof import('./components/LabelWithTooltip/LabelWithTooltip.vue')['default']
    MoreActions: typeof import('./components/MoreActions/MoreActions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/SearchBar/SearchBar.vue')['default']
    TabsView: typeof import('./components/TabsView/TabsView.vue')['default']
    WangEditor: typeof import('./components/WangEditor/WangEditor.vue')['default']
  }
}
